config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users

  root 'talks#index'

  resources :talks do
    resources :references
  end

  get 'upcoming_talks' => 'talks#upcoming_talks', as: 'upcoming_talks'
  get 'recent_talks' => 'talks#recent_talks', as: 'recent_talks'
  get 'about_me' => 'talks#about_me', as: 'about_me'
  get 'search' => 'talks#search'
  get 'talks/:id/addslide' => 'talks#add_slide', as: 'add_slide'
  match 'download_slide/:id', to: 'talks#download_slide', as: 'download_slide', via: :get

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/talk.rb
# frozen_string_literal: true

class Talk < ApplicationRecord
  belongs_to :user
  has_many :references, dependent: :destroy
  mount_uploader :slide, SlideUploader
  validates :title, presence: true
  validates :date, presence: true
  validates :location, presence: true
  validates :description, presence: true
end

app/controllers/talks_controller.rb
# frozen_string_literal: true

class TalksController < ApplicationController
  before_action :authenticate_user!
  before_action :set_talk, only: %i[show edit update destroy add_slide]

  # method to get list of all talks from past and future
  def index
    @talks = Talk.all.order(date: :desc)
  end

  # method to get list of all talks upcoming talks (future)
  def upcoming_talks
    @talks = Talk.where('date > ?', DateTime.now).order(date: :asc)
  end

  # method to get list of all talks recent talks (past)
  def recent_talks
    @talks = Talk.where('date < ?', DateTime.now).order(date: :asc)
  end

  # method to get search results
  def search
    @search_term = params[:search]
    @talks = Talk.where('title like ?', "%#{@search_term}%")
  end

  # This method will redirect to form to create a new talk event
  def new
    @talk = Talk.new
  end

  # method to insert data to database(create)
  def create
    @user = current_user
    @talk = @user.talks.new(talk_params)
    if @talk.save
      flash[:success] = 'Talk Added Successfully!'
      redirect_to @talk
    else
      render 'new'
    end
  end

  # method to show individual talk. It receives @talk variable from set_talk method called before action
  def show; end

  # method to redirect to edit page. It receives @talk variable from set_talk method called before action
  def edit; end

  # method to update talk details. It receives @talk variable from set_talk method called before action
  def update
    if @talk.update(talk_params)
      flash[:success] = 'Talk Updated!'
      redirect_to @talk
    else
      render 'edit'
    end
  end

  # method to delete the talk. It receives @talk variable from set_talk method called before action
  def destroy
    @talk.destroy
    flash[:danger] = 'Talk Deleted!'
    redirect_to root_path
  end

  # method to redirect user to his profile
  def about_me; end

  # method to redirect to add slide page. It receives @talk variable from set_talk method called before action
  def add_slide; end

  # method to download the slide
  def download_slide
    download_file = Talk.find(params[:id]).slide
    send_file download_file.path, status: 202
  end

  # method for security of input params
  private

  def talk_params
    params.require(:talk).permit(:title, :location, :date, :description, :slide)
  end

  # method which is common for all to set talk by finding id
  def set_talk
    @talk = Talk.find(params[:id])
  end
end

app/helpers/talks_helper.rb
# frozen_string_literal: true

module TalksHelper
end

app/views/talks/_form.html.erb
<%= form_with model: @talk, local: true do |form| %>
 
  <% if @talk.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@talk.errors.count, "error") %> prohibited
        this talk from being saved:
      </h2>
      <ul>
        <% @talk.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <p>
    <%= form.label :title %><br>
    <%= form.text_field :title, :class => "form-control" %>
  </p>

  <p>
    <%= form.label :location %><br>
    <%= form.text_field :location, :class => "form-control" %>
  </p>

  <p>
    <%= form.label :date %><br>
    <%= form.date_field :date, :class => "form-control" %>
  </p>

  <p>
    <%= form.label :description %><br>
    <%= form.text_area :description, :class => "form-control" %>
  </p>
 
  <p>
    <%= form.submit :class => 'btn btn-success' %>
  </p>
 
<% end %>

app/views/talks/_table.html.erb
<div class="card-body">
    <table class="table table-striped table-bordered">
      <thead>
        <tr>
          <th>Date</th>
          <th>Talk Title</th>
          <th>Speaker</th>
          <th>Location</th>
          <th>Action</th>
        </tr>
      </thead>
      <tbody>
        <% @talks.each do |talk| %>
          <tr>
              <td><%= talk.date.strftime("%d %B,%Y") %></td>
              <td><%= talk.title %></td>
              <td><%= talk.user.email %></td>
              <td><%= talk.location %></td>
              <td>
                <%= link_to "View",talk_path(talk),:class=>"btn btn-sm btn-primary text-white" %>
                
                <% if current_user == talk.user %>
                  <%= link_to "Edit",edit_talk_path(talk),:class=>"btn btn-sm btn-warning text-white" %>
                  <%= link_to 'Delete', talk_path(talk),
                  method: :delete , data: { confirm: 'Are you sure?'},:class=>"btn btn-sm btn-danger text-white" %>
                  <%= link_to "Add Slide",add_slide_path(talk),:class=>"btn btn-sm btn-primary text-white" %>
                  <% end %>
              </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>

app/views/talks/about_me.html.erb
<div class="card mt-5">
  <div class="card-body">
    <strong>Currently logged in as : <%= current_user.email %></strong>
    <br>
    <strong>Role : <%= current_user.admin ? 'Admin' : 'User' %> </strong>
  </div>
</div>

app/views/talks/add_slide.html.erb
<div class="card mt-5">
  <h4 class="card-header">Add Slide for '<%= @talk.title %>' event </h4>
  <div class="card-body">
    <%= form_for @talk do |f| %>
      <div class="field form-control">
        <label>Add Slide : </label>
        <%= f.file_field :slide %>
      </div>

      <%= f.submit "Add", :class=>"btn btn-success mt-2" %>

    <% end %>
  </div>
  <div class="card-footer">
    <%= link_to "Back", :back ,:class=>"btn btn-secondary text-white" %>
  </div>
</div>

app/views/talks/edit.html.erb
<div class="card mt-5">
  <h2 class="card-header">Schedule a Talk Event</h2>
  <div class="card-body">
    <%= render 'form' %>
  </div>
</div>

app/views/talks/index.html.erb
<div class="mt-2 jumbotron">
  <h2 class="text-center text-info">Lunch And Learn Manager</h2>
  <p>
  Get all information about all the talk events happening near you 
  where you can eat and learn at one place and meet incredible peoples
  from different fields.
  </p>
</div>
<div class="card">
  <h2 class="card-header">All Talks List</h2>
  <%= render "table" %>
</div>

app/views/talks/new.html.erb
<div class="card mt-5">
  <h2 class="card-header">Schedule a Talk Event</h2>
  <div class="card-body">
    <%= render 'form' %>
  </div>
</div>

app/views/talks/recent_talks.html.erb
<div class="card mt-5">
  <h2 class="card-header">All Recent Talks List</h2>
  <%= render "table" %>
</div>

app/views/talks/search.html.erb
<% unless @talks.empty? %>
  <h5 class="text-info mt-4">Showing results for '<%= @search_term %>' (<%= @talks.count %>) results found.</h5>
  <hr>
  <% @talks.each do |talk| %>
    <div class="card mb-2">
      <div class="card-header"><%= talk.title %></div>
      <div class="card-body">
        <h6>Speaker : <%= talk.user.email %></h6>
        <h6>Date : <%= talk.date.strftime("%d %B,%Y") %></h6>
        <h6>Location : <%= talk.location %></h6>
      </div>
      <div class="card-footer">
      <%= link_to "View",talk_path(talk),:class=>"btn btn-primary text-white" %>
      
      <% if current_user == talk.user %>
      <%= link_to "Edit",edit_talk_path(talk),:class=>"btn btn-warning text-white" %>
      <%= link_to 'Delete', talk_path(talk),
      method: :delete , data: { confirm: 'Are you sure?'},:class=>"btn btn-danger text-white" %>
      
      <% end %>
      </div>
    </div>
  <% end %>
<% else %>
    <h5 class="text-danger mt-4">Sorry no results found for '<%= @search_term %>'</h5>
<% end %>

app/views/talks/show.html.erb
<div class="card mt-5">
  <h3 class="card-header">
    <%= @talk.title %> Event
  </h3>
  <div class="card-body">
    <h5>Speaker : <%= @talk.user.email %> </h5>
    <h5>Title : <%= @talk.title %> </h5>
    <h5>Date : <%= @talk.date.strftime("%d %B,%Y") %> </h5>
    <h5>Location : <%= @talk.location %> </h5>
    <h5>Description : <%= @talk.description %> </h5>
    
    <% if @talk.slide.present? %>
      <hr>
      <iframe src= <%= @talk.slide.url.html_safe %> width="400" height="400" frameborder="0" marginwidth="0" marginheight="0" scrolling="no" style="border:1px solid #CCC; border-width:1px; margin-bottom:5px; max-width: 100%;" allowfullscreen> </iframe>
      <%= link_to "Download Slide of the talk event", download_slide_path(@talk), target: "_blank"%>
    <% end %>

    <% if @talk.references.present? %>
      <hr>
      <div class="card">
        <div class="card-header">References</div>
          <div class="card-body">
            <ul>
              <% @talk.references.each do |ref| %>
                <li>  
                <div class="row">  
                  <%= link_to ref.body , ref.body , target: "_blanck", :class=>"col-md-11" %>
                    <% if current_user == @talk.user %>
                    <%= link_to 'X', talk_reference_path(@talk,ref),
                      method: :delete , data: { confirm: 'Are you sure?'},:class=>"text-danger col-md-1" %>
                    <% end %>
                  </div>
                </li>
              <% end %>
            </ul>
          </div>
      </div>  
    <% end %>
    <hr>
  <% if current_user == @talk.user %>              
    <div class="card">
      <div class="card-header">Add a Reference:</div>
      <div class="card-body">
        <%= form_with(model: [ @talk, @talk.references.build ], local: true) do |form| %>
          <p>
            <%= form.text_area :body , :class=>"form-control" %>
          </p>
          <p>
            <%= form.submit "Add References", :class=>"btn btn-success" %>
          </p>
        <% end %>
      </div>
    </div>
  <% end %>

  </div>
  <div class="card-footer">
  <%= link_to "Back", :back ,:class=>"btn btn-secondary text-white" %>
  
  <% if current_user == @talk.user %>
  <%= link_to "Edit",edit_talk_path(@talk),:class=>"btn btn-warning text-white" %>
  <%= link_to "Add Slide",add_slide_path(@talk),:class=>"btn btn-primary text-white" %>
  <%= link_to 'Delete', talk_path(@talk),
  method: :delete , data: { confirm: 'Are you sure?'},:class=>"btn btn-danger text-white" %>
  <% end %>
  </div>
</div>

app/views/talks/upcoming_talks.html.erb
<div class="card mt-5">
  <h2 class="card-header">All Upcoming Talks List</h2>
  <%= render "table" %>
</div>