config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users

  root 'talks#index'

  resources :talks do
    resources :references
  end

  get 'upcoming_talks' => 'talks#upcoming_talks', as: 'upcoming_talks'
  get 'recent_talks' => 'talks#recent_talks', as: 'recent_talks'
  get 'about_me' => 'talks#about_me', as: 'about_me'
  get 'search' => 'talks#search'
  get 'talks/:id/addslide' => 'talks#add_slide', as: 'add_slide'
  match 'download_slide/:id', to: 'talks#download_slide', as: 'download_slide', via: :get

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/common/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-primary mt-2">
  <%= link_to "Lunch&Learn Manager", root_path, :class=>"navbar-brand text-white" %>

  <form class="form-inline my-2 ml-5 my-lg-0" method="get" action="../search">
      <input class="form-control mr-sm-2" type="search" name="search" placeholder="Search Talk" aria-label="Search">
      <button class="btn btn-success my-2 my-sm-0" type="submit">Search</button>
  </form>

  <div class="collapse navbar-collapse">
    <ul class="navbar-nav ml-auto">
      <li class="nav-item">
        <%= link_to "All Talks", root_path, :class=>"nav-link text-white"  %>
      </li>
      <li class="nav-item">
        <%= link_to "Schedule Talk", new_talk_path, :class=>"nav-link text-white"  %>
      </li>
      <li class="nav-item">
        <%= link_to "Upcoming Talks", upcoming_talks_path, :class=>"nav-link text-white"  %>
        <div id="count"></div>
      </li>
      <li class="nav-item">
        <%= link_to "Recent Talks", recent_talks_path, :class=>"nav-link text-white"  %>
      </li>
      <% if current_user.admin? %>
        <li class="nav-item">
          <%= link_to "New Invitation", new_user_invitation_path, :class=>"nav-link text-white"  %>
        </li>
      <% end %>
      <li class="nav-item">
        <%= link_to "About Me", about_me_path, :class=>"nav-link text-white" %>
      </li> 
      <li class="nav-item">
        <%= link_to "Log Out", destroy_user_session_path, method: :delete, :class=>"nav-link text-white" %>
      </li>  
    </ul>    
  </div>      
</nav>        